services:
  # Order Service (Main Application)
  order-service:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/accenture
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=321
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - db
      - redis

  # PostgreSQL Database Service
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=accenture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=321
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # Redis Cache Service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
