DROP TABLE IF EXISTS order_items, orders CASCADE;

-- Creamos la tabla orders
CREATE TABLE orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT         NOT NULL,
    order_amount DECIMAL(10, 2) NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Creamos la tabla  order_items
CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT REFERENCES orders (id) ON DELETE CASCADE,
    product_id BIGINT         NOT NULL,
    quantity   INT            NOT NULL,
    price      DECIMAL(10, 2) NOT NULL
);

-- Creamos indexes
CREATE INDEX idx_orders_customer_id ON orders (customer_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);