spring:
  data:
    redis:
      host: redis
      port: 6379

  application:
    name: challenge

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DB:accenture}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:321}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  cache:
    type: redis

  task:
    execution:
      pool:
        core-size: 50
        max-size: 250
        queue-capacity: 1000

server:
  port: ${SERVER_PORT:8080}
